version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: basket_craft_dw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basket_craft_dw
    ports:
      - "5432:5432"
    volumes:
      - basket_craft_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  basket_craft_data:
